include:
  - remote: https://gitlab.com/ynezz/openwrt-ci/raw/master/openwrt-ci/gitlab/main.yml

check shell scripts with shellcheck:
  extends: .openwrt-shellcheck

check Python scripts with black and flake8:
  extends: .openwrt-pythoncheck
